import type { Metadata } from "next";
import Header from "@/app/components/Header"
import "./globals.css"; // Ensure this exists in your root layout
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
     
    >
      <body className="min-h-full flex flex-col">
           {/* Header Section */}
    <div className="min-h-screen bg-slate-900 text-slate-100 flex flex-col items-center justify-start p-6 sm:p-12">
      <div className="w-full max-w-2xl space-y-6">
        <Header>
        </Header>
        {children}
        </div>
        </div>
      
        </body>
    </html>
  );
}
